name = "blogish"

[output]
name = 'build'
type = 'js'
main = 'Blogish'
sourceFolder = 'example/blogish/src'
target = 'static'

[server]
type = 'node'
port = 8080

[dependencies]
shared = ['breeze', 'blok.foundation']
server = ['hxnodejs', 'mime', 'toml', 'markdown']

# [build.flags]
# js-es = 6
# message-reporting = 'pretty'
# 'breeze.output' = 'none'
# analyzer-optimize = true
