name = "blogish"

[output]
type = 'js'
path = 'dist/build.js'
main = 'Blogish'
sourceFolder = 'example/blogish/src'

[dependencies]
shared = ['breeze', 'blok.foundation']
server = ['hxnodejs', 'mime', 'toml', 'markdown']

[server]
type = 'node'
port = 8080

[path]
# staticPrefix = '/public'
assetPath = '/assets'
apiPrefix = '/api'
apiPath = '/api'


# [build.flags]
# js-es = 6
# message-reporting = 'pretty'
# 'breeze.output' = 'none'
# analyzer-optimize = true
