name = 'blogish'
version = '0.0.1'
type = 'static'

[dependencies]
shared = ['breeze', 'blok.foundation']
server = ['hxnodejs', 'mime', 'toml', 'markdown']

[path]
# staticPrefix = '/public'
assetPath = '/assets'
apiPrefix = '/api'
apiPath = '/api'

[output]
type = 'js'
path = 'dist/build.js'
main = 'Blogish'
src = 'example/blogish/src'

[output.flags.shared]
js-es = '6'
message-reporting = 'pretty'
analyzer-optimize = true
debug = true

[output.flags.server]
'breeze.output' = 'none'

[output.flags.client]
'breeze.output' = 'runtime'
