name = 'blogish'
version = '0.0.1'
type = 'static'

[dependencies]
shared = ['breeze', 'blok.foundation']
server = ['hxnodejs', 'mime', 'toml', 'markdown']

[path]
# staticPrefix = '/public'
assetPath = '/assets'
apiPrefix = '/api'
apiPath = '/api'

[assets]
src = 'example/blogish/data'
public = 'dist/www'
private = 'dist'

[haxe]
src = 'example/blogish/src'
main = 'Blogish'
target = 'js'
output = 'dist/build.js'

[haxe.flags.shared]
js-es = '6'
message-reporting = 'pretty'
analyzer-optimize = true
'breeze.output' = 'styles-{{version}}'
